apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  namespace: keycloak
spec:
  storageClassName: keycloak
  claimRef:
    name: keycloak-volume
    namespace: keycloak
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/data/
  nodeAffinity:
   required:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - cpu1
