
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-volume
  namespace: keycloak
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: keycloak
