apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: dns
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            upstream
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        rewrite name regex (.*)\.192\.168\.1\.242\.xip\.io abs.nginx
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
    }

