apiVersion: v1
kind: Service
metadata:
  name: dns-service
  namespace: dns
spec:
  type: LoadBalancer
  selector:
    app: dns-server
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53

