apiVersion: v1
kind: PersistentVolume
metadata:
  name: directus-db-pv
  namespace: directus-dev
spec:
  storageClassName: directus   # Use the new StorageClass
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/your/host/database/folder"
