apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-db-pvc
  namespace: directus-dev
spec:
  storageClassName: directus   # Use the new StorageClass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
