apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-color-deployment
  namespace: sathish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-color-app
  template:
    metadata:
      labels:
        app: node-color-app
    spec:
      containers:
        - name: node-color-container
          image: sathishin2k/node-color:v1
          ports:
            - containerPort: 3000
