apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-user
  namespace: postgres  # Replace with the appropriate namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-user-binding
roleRef:
  kind: ClusterRole
  name: view  # Replace with an appropriate ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: external-user
    namespace: postgres # Same namespace as the ServiceAccount
