apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvcss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: slows
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs-pvcss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: slows
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvcss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: slows
