apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app-deployment
  namespace: sathish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-app
  template:
    metadata:
      labels:
        app: color-app
    spec:
      containers:
        - name: color-app-container
          image: sathishin2k/color-app:v1
          env:
            - name: COLOR
              value: "Gray"  
