apiVersion: v1
kind: PersistentVolume
metadata:
  name: directus-database-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: directus
  hostPath:
    path: /directus-volume/database

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: directus-uploads-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: directus
  hostPath:
    path: /directus-volume/uploads
