apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-data-pvc
  namespace: directus-dev
spec:
  storageClassName: directus-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
