apiVersion: v1
kind: PersistentVolume
metadata:
  name: directus-uploads-pv
  namespace: directus-dev
spec:
  storageClassName: directus-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/directus-uploads
