apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-server
    spec:
      containers:
        - name: argocd-server
          image: quay.io/argoproj/argocd:v2.8.0  # Use the latest version
          ports:
            - containerPort: 8080

