apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/gitlab

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/log/gitlab

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/opt/gitlab
