apiVersion: apps/v1
kind: Deployment
metadata:
  name: myscript-deployment
  namespace: aaron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myscript
  template:
    metadata:
      labels:
        app: myscript
    spec:
      containers:
      - name: myscript-container
        image: aaronabs/myscript:v1
        env:
        - name: color
          value: "coral"
